### ISSUE TITLE
which default font pick by android and ios if we not provided font-family

### ISSUE THREAD

**Issue by jariwalabhavesh** [react-native-training/react-native-fonts#6]
which default font pick by android and ios if we not provided font-family?

**Comment by dabit3** [comment]
I believe iOS is San Francisco and Android is Roboto

**Comment by jariwalabhavesh** [comment]
Thanks @dabit3 for response

**Comment by deepaksisodiya** [comment]
@dabit3 Is this the default behaviour of React Native?
